### ISSUE TITLE
vmedia_mount_remove_all can't handle saved vmedia mappings

### ISSUE THREAD

**Issue by jlothian** [CiscoUcs/imc-ansible#20]
If a CIMC has a saved but inactive vmedia mapping, vmedia_mount_remove_all will throw the following exception:

`[2018-03-26 10:00:02] 10.23.223.248 Caught an exception: Traceback (most recent call last):
  File "/home/jlothian/src/cimc-cli/cimc_cli/firmwarecommands.py", line 22, in upgrade_firmware
    result = firmware.upgrade(handle, location)  # FW upgrades either work, or raise an Exception
  File "/home/jlothian/src/cimc-cli/cimc_cli/firmware.py", line 46, in upgrade
    vmedia_mount_remove_all(handle)
  File "/home/jlothian/.virtualenvs/cimc-cli/local/lib/python2.7/site-packages/imcsdk/apis/server/vmedia.py", line 409, in vmedia_mount_remove_all
    handle.remove_mo(virt_media)
  File "/home/jlothian/.virtualenvs/cimc-cli/local/lib/python2.7/site-packages/imcsdk/imchandle.py", line 484, in remove_mo
    self._commit(timeout=timeout)
  File "/home/jlothian/.virtualenvs/cimc-cli/local/lib/python2.7/site-packages/imcsdk/imchandle.py", line 517, in _commit
    response = self.post_elem(elem, timeout=timeout)
  File "/home/jlothian/.virtualenvs/cimc-cli/local/lib/python2.7/site-packages/imcsdk/imcsession.py", line 287, in post_elem
    response = xc.from_xml_str(response_str, self)
  File "/home/jlothian/.virtualenvs/cimc-cli/local/lib/python2.7/site-packages/imcsdk/imcxmlcodec.py", line 91, in from_xml_str
    raise ex.ImcException(error_code, error_descr)
ImcException: [ErrorCode]: ERR-xml-parse-error[ErrorDescription]: XML PARSING ERROR: Element 'commSavedVMediaMap': The attribute 'adminAction' is required but missing. 
`

This is on 0.9.3.0.

**Comment by jlothian** [comment]
Whoops, wrong project
